### ISSUE TITLE
https://github.com/aboba/edgertc/pull/16# issues with bitmask

### ISSUE THREAD

**Issue by FrankLi-MS** [aboba/edgertc#22]
Need to sort out bitmasks of audioCaptureDeviceErrorFlags, captureDeviceAudioCaptureDeviceErrorFlagsInit, audioRenderDeviceErrorFlags, introduced by PR#16.
If it were real bit mask, these should be modeled as MSIceWarningFlags.

**Comment by msdazhou** [comment]
Looked at MSIceWarningFlags, it is ULONG in ortcEngine but a dictionary in the Spec. Does javascript layer convert the type?

**Comment by FrankLi-MS** [comment]
EdgeHTML converts it for JS to consume.
________________________________

**Comment by msdazhou** [comment]
So we can do similarly for audioCaptureDeviceErrorFlags, captureDeviceAudioCaptureDeviceErrorFlagsInit, audioRenderDeviceErrorFlags?

**Comment by aboba** [comment]
@FrankLi-MS @msdazhou Are these really going to be implemented as bitmasks or as generic errors (e.g. from MF)?

**Comment by FrankLi-MS** [comment]
@Aboba, Per discussion: please remove:     unsigned long long audioCaptureDeviceErrorFlags;
    unsigned long audioSourceSessionDisconnectReason;
    unsigned long long captureDeviceAudioCaptureDeviceErrorFlagsInit;  from MSAudioSendPayload   AND
    unsigned long long audioRenderDeviceErrorFlags;
    unsigned long audioSinkSessionDisconnectReason;  from MSAudioRecvPayload
