### ISSUE TITLE
MSTransportDiagnosticsStats has two localInterface members

### ISSUE THREAD

**Issue by FrankLi-MS** [aboba/edgertc#30]
localInterface of type MSNetworkInterfaceType
Local interface type selected for media flow at end of connectivity checks.
localInterface of type DOMString
Local interface used for connectivity checks.

"localInterface of type DOMString" should be MSNetworkInterfaceType too in case it is not a dupe ?

**Comment by aboba** [comment]
@FrankLi-MS Have confirmed that this is a duplicate.
