### ISSUE TITLE
MSAudioRecvPayload has audioLoopbackDeviceErrorFlags without doc

### ISSUE THREAD

**Issue by FrankLi-MS** [aboba/edgertc#31]
Should we convert audioLoopbackDeviceErrorFlags to dictionary type or doc the meaning of the bit flags?

**Comment by msdazhou** [comment]
Do we need this since we have removed the other audio device error flags

**Comment by FrankLi-MS** [comment]
Oh right. It seems we should remove it too as ADSP won't able to provide it anyway.
